export const featuredProducts = [
  {
    id: "1",
    title: "Organic Mountain Water",
    price: "$2.99",
    image: "/placeholder.svg",
    category: "Beverages",
    rating: 4.5,
    reviewCount: 128,
  },
  {
    id: "2",
    title: "Fresh Baked Croissant",
    price: "$3.99",
    image: "/placeholder.svg",
    category: "Breads & Bakery",
    rating: 4.8,
    reviewCount: 256,
  },
  {
    id: "3",
    title: "Premium Dark Chocolate",
    price: "$4.99",
    salePrice: "$3.99",
    image: "/placeholder.svg",
    category: "Snacks & Candy",
    rating: 4.7,
    reviewCount: 189,
    badge: "Sale",
  },
  {
    id: "4",
    title: "Artisan Coffee Beans",
    price: "$12.99",
    image: "/placeholder.svg",
    category: "Beverages",
    rating: 4.9,
    reviewCount: 342,
  },
  {
    id: "5",
    title: "Sourdough Bread",
    price: "$5.99",
    image: "/placeholder.svg",
    category: "Breads & Bakery",
    rating: 4.6,
    reviewCount: 167,
  }
] 