export const featuredProducts = [
    {
      id: "p1",
      title: "Pepsi-Cola Cherry Coke 12oz Pack",
      price: "$12",
      salePrice: "$10",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.5,
      reviewCount: 24,
      category: "Beverages",
      slug: "pepsi-cola-cherry",
    },
    {
      id: "p2",
      title: "Guinness Draught Can Triple Six Pack",
      price: "$11",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.8,
      reviewCount: 36,
      category: "Beverages",
      slug: "guinness-draught",
    },
    {
      id: "p3",
      title: "Heinz Dr Pepper Dr Fizz Fruit Cream",
      price: "$10",
      salePrice: "$9",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.2,
      reviewCount: 18,
      category: "Beverages",
      slug: "heinz-dr-pepper",
    },
    {
      id: "p4",
      title: "Pepsi Exotic Selection 16oz Coke Blast 6X 2",
      price: "$17",
      salePrice: "$14",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.7,
      reviewCount: 42,
      badge: "HOT",
      category: "Beverages",
      slug: "pepsi-exotic",
    },
    {
      id: "p5",
      title: "Malt Dr Cream Seltzer Mineral Beverage Soda",
      price: "$11",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.3,
      reviewCount: 15,
      category: "Beverages",
      slug: "malt-dr-cream",
    },
    // Add more products for other categories
    {
      id: "p6",
      title: "Fresh Baked Sourdough Bread",
      price: "$5",
      salePrice: "$4",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.9,
      reviewCount: 28,
      category: "Breads & Bakery",
      slug: "sourdough-bread",
    },
    {
      id: "p7",
      title: "Chocolate Chip Cookies 12-Pack",
      price: "$7",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.7,
      reviewCount: 32,
      category: "Breads & Bakery",
      slug: "chocolate-chip-cookies",
    },
    {
      id: "p8",
      title: "Doritos Nacho Cheese Flavored Tortilla Chips",
      price: "$4",
      salePrice: "$3.50",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.6,
      reviewCount: 45,
      category: "Snacks & Candy",
      slug: "doritos-nacho-cheese",
    },
    {
      id: "p9",
      title: "Hershey's Milk Chocolate Bar 6-Pack",
      price: "$6",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.8,
      reviewCount: 38,
      category: "Snacks & Candy",
      slug: "hersheys-chocolate",
    },
  ]
  
  