export const beverageProducts = [
    {
      id: "b1",
      title: "Jim Beam & Coca-Cola Ready To Drink Bottle 330ml",
      price: "$12.99",
      salePrice: "$10.99",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.5,
      reviewCount: 28,
      badge: "SALE",
      category: "Beverages",
      slug: "jim-beam-coca-cola",
    },
    {
      id: "b2",
      title: "JOHNNIE WALKER Black Label Blended Scotch Whisky 700ml",
      price: "$39.99",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.8,
      reviewCount: 56,
      badge: "SALE",
      category: "Beverages",
      slug: "johnnie-walker-black",
    },
    {
      id: "b3",
      title: "PERRIER Carbonated Mineral Water 330ml Bottles",
      price: "$24.99",
      salePrice: "$19.99",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.7,
      reviewCount: 32,
      badge: "SALE",
      category: "Beverages",
      slug: "perrier-carbonated",
    },
    {
      id: "b4",
      title: "LIPTON Ice Tea Peach Flavored Iced Tea 500ml",
      price: "$3.99",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.3,
      reviewCount: 24,
      badge: "SALE",
      category: "Beverages",
      slug: "lipton-ice-tea",
    },
    {
      id: "b5",
      title: "Schweppes Tonic Water 600ml",
      price: "$2.99",
      salePrice: "$1.99",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.5,
      reviewCount: 18,
      badge: "SALE",
      category: "Beverages",
      slug: "schweppes-tonic",
    },
    {
      id: "b6",
      title: "Moet & Chandy Champagne 750ml",
      price: "$49.99",
      salePrice: "$39.99",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.8,
      reviewCount: 42,
      badge: "SALE",
      category: "Beverages",
      slug: "moet-chandy",
    },
    {
      id: "b7",
      title: "Evian Natural Spring Water 500ml",
      price: "$1.99",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.2,
      reviewCount: 16,
      badge: "SALE",
      category: "Beverages",
      slug: "evian-spring-water",
    },
    {
      id: "b8",
      title: "Jack Daniel's Tennessee Whiskey 700ml",
      price: "$35.99",
      salePrice: "$29.99",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.7,
      reviewCount: 38,
      badge: "SALE",
      category: "Beverages",
      slug: "jack-daniels",
    },
  ]
  
  